server:
  port: 8083

spring:
  application:
    name: audit-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: audit-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.notifymesh.*
      auto-offset-reset: earliest
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}

notifymesh:
  kafka:
    topic:
      notification-delivered: notification.delivered
      notification-failed: notification.failed
  elasticsearch:
    index:
      deliveries: notifymesh-deliveries

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when-authorized
