server:
  port: 8084

spring:
  application:
    name: query-service
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}

notifymesh:
  elasticsearch:
    index:
      deliveries: notifymesh-deliveries

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when-authorized
